import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', e => { errors.push(e.message); console.log('ERROR', e.message); });
page.on('console', m => { if (m.type() === 'error') { errors.push(m.text()); console.log('CONSOLE', m.text()); } });
const state = () => page.evaluate(() => window.__litoral.state);
try {
  await page.goto('http://127.0.0.1:5175/?test');
  await page.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  console.log('INITIAL', await state());
  assert.equal((await state()).character, 'female');
  await page.click('#intro-character');
  await page.waitForTimeout(900);
  await page.screenshot({ path: 'test-results/female-full.png' });
  await page.click('[data-portrait="face"]');
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'test-results/female-face.png' });
  await page.click('#character-confirm');
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'test-results/female-play.png' });
  console.log('PLAY', await state());
  await page.keyboard.down('w'); await page.waitForTimeout(700);
  await page.screenshot({ path: 'test-results/female-walk.png' });
  await page.keyboard.up('w');
  console.log('WALK', await state());
  await page.keyboard.down('Shift'); await page.keyboard.down('w'); await page.waitForTimeout(700);
  await page.screenshot({ path: 'test-results/female-run.png' });
  await page.keyboard.up('w'); await page.keyboard.up('Shift');
  await page.keyboard.press('Space'); await page.waitForTimeout(170);
  await page.screenshot({ path: 'test-results/female-jump.png' });
  await page.waitForTimeout(900);
  await page.click('#character-open'); await page.click('[data-character="male"]');
  await page.click('[data-portrait="full"]'); await page.waitForTimeout(350);
  await page.screenshot({ path: 'test-results/male-full.png' });
  await page.click('#character-confirm'); await page.waitForTimeout(200);
  assert.equal((await state()).character, 'male');
  console.log('MALE', await state());
  await page.reload(); await page.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  assert.equal((await state()).character, 'male');
  await page.click('#intro-character'); await page.click('[data-character="female"]');
  await page.keyboard.press('Escape'); await page.waitForTimeout(150);
  assert.equal((await state()).character, 'male');
  assert.equal((await state()).mode, 'intro');
  assert.deepEqual(errors, []);
  console.log('PASS female default, preview, locomotion, male switching, persistence, cancellation, no errors');
} finally { await browser.close(); }
