import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [], checks = [];
function track(target) {
  target.on('pageerror', e => errors.push(e.message));
  target.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  target.on('response', r => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
}
track(page);
const state = () => page.evaluate(() => window.__litoral.state);
const check = (name, value) => { assert.ok(value, name); checks.push(name); console.log('PASS', name); };
try {
  await page.goto('http://127.0.0.1:5175/?test');
  await page.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  check('female is selected by default', (await state()).character === 'female');
  await page.click('#intro-character');
  await page.waitForTimeout(900);
  const canvas = await page.locator('#avatar-preview').boundingBox();
  check('desktop preview fits inside the dialog', canvas.width > 500 && canvas.y + canvas.height <= 900);
  await page.screenshot({ path: 'test-results/female-full.png' });
  await page.click('[data-portrait="face"]');
  check('face view has selected state', await page.locator('[data-portrait="face"]').getAttribute('aria-pressed') === 'true');
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'test-results/female-face.png' });
  await page.click('#character-confirm');
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'test-results/female-play.png' });
  check('confirmation starts play', (await state()).mode === 'playing');
  const beforeWalk = await state();
  await page.keyboard.down('w'); await page.waitForTimeout(700);
  await page.screenshot({ path: 'test-results/female-walk.png' });
  await page.keyboard.up('w');
  const walking = await state();
  check('female walks with the controller', walking.z < beforeWalk.z - 1 && Math.hypot(walking.avatarCenter[0] - walking.x, walking.avatarCenter[2] - walking.z) < .5);
  check('retargeted walk preserves human proportions', walking.avatarHeight > 1.5 && walking.avatarHeight < 1.9 && Math.abs(walking.avatarGround - walking.y) < .25);
  await page.keyboard.down('Shift'); await page.keyboard.down('w'); await page.waitForTimeout(700);
  await page.screenshot({ path: 'test-results/female-run.png' });
  check('female can sprint', (await state()).running && (await state()).speed > 5);
  await page.keyboard.up('w'); await page.keyboard.up('Shift');
  await page.keyboard.press('Space'); await page.waitForTimeout(170);
  check('female can jump', (await state()).y > .5);
  await page.screenshot({ path: 'test-results/female-jump.png' });
  await page.waitForTimeout(900);
  check('female lands on the ground', (await state()).grounded && (await state()).y === .16);
  const beforeSwitch = await state();
  await page.click('#character-open'); await page.click('[data-character="male"]');
  await page.keyboard.down('w'); await page.waitForTimeout(200); await page.keyboard.up('w');
  check('preview does not move the player or apply a pending choice', Math.abs((await state()).z - beforeSwitch.z) < .01 && (await state()).character === 'female');
  await page.click('[data-portrait="full"]'); await page.waitForTimeout(350);
  await page.screenshot({ path: 'test-results/male-full.png' });
  await page.click('#character-confirm'); await page.waitForTimeout(200);
  check('confirmed choice switches to male', (await state()).character === 'male');
  check('switching preserves position and progress', Math.abs((await state()).z - beforeSwitch.z) < .01 && JSON.stringify((await state()).found) === JSON.stringify(beforeSwitch.found));
  await page.keyboard.press('Escape'); await page.click('#pause-character');
  await page.click('[data-character="female"]'); await page.keyboard.press('Escape'); await page.waitForTimeout(100);
  check('cancelling from pause restores pause and original character', await page.locator('#pause-dialog').isVisible() && (await state()).mode === 'paused' && (await state()).character === 'male');
  await page.click('#resume');
  await page.reload(); await page.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  check('character choice survives reload', (await state()).character === 'male');
  await page.click('#intro-character'); await page.click('[data-character="female"]');
  await page.keyboard.press('Escape'); await page.waitForTimeout(150);
  check('cancelling from intro restores intro and original character', (await state()).character === 'male' && (await state()).mode === 'intro');

  const mobile = await browser.newPage({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true });
  track(mobile);
  await mobile.goto('http://127.0.0.1:5175/');
  await mobile.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  await mobile.click('#intro-character'); await mobile.waitForTimeout(400);
  await mobile.screenshot({ path: 'test-results/mobile-character.png' });
  check('mobile selector fits without horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.querySelector('#character-dialog').scrollWidth <= innerWidth));
  const confirm = await mobile.locator('#character-confirm').boundingBox();
  check('mobile confirm is visible without scrolling', confirm.height >= 44 && confirm.y + confirm.height <= 812);
  await mobile.click('[data-portrait="face"]'); await mobile.waitForTimeout(300);
  await mobile.screenshot({ path: 'test-results/mobile-character-face.png' });
  await mobile.click('[data-character="male"]'); await mobile.click('#character-confirm'); await mobile.waitForTimeout(100);
  check('mobile selection applies to actual gameplay', await mobile.evaluate(() => window.__litoral.state.character === 'male' && window.__litoral.state.mode === 'playing'));
  await mobile.click('#character-open'); await mobile.click('[data-character="female"]'); await mobile.click('#character-confirm'); await mobile.waitForTimeout(100);
  check('mobile switches back to female during play', await mobile.evaluate(() => window.__litoral.state.character === 'female'));
  await mobile.close();
  check('no browser, asset, or WebGL errors', errors.length === 0);
  await writeFile('test-results/character-results.json', JSON.stringify({ checks, errors }, null, 2));
  console.log(`${checks.length} character checks passed.`);
} finally { await browser.close(); }
