import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const errors = [], checks = [];
const check = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log('PASS', name); };
function track(page) {
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('response', r => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
}
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } }); track(page);
const state = () => page.evaluate(() => window.__morning.state);
const go = async id => { await page.evaluate(id => window.__morning.goTo(id), id); await page.waitForTimeout(100); };
try {
  await page.goto('http://127.0.0.1:5176/?test');
  await page.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  await page.screenshot({ path: 'test-results/01-intro.png' });
  await page.click('#start');
  check('new game starts as adult male', (await state()).character === 'male');
  const before = await state();
  await page.keyboard.down('w'); await page.waitForTimeout(850); await page.keyboard.up('w');
  check('W moves the male through the room', (await state()).z < before.z - .35);
  await page.screenshot({ path: 'test-results/02-male.png' });
  await page.keyboard.press('e');
  check('interaction outside range cannot possess remotely', (await state()).character === 'male');
  await go('possess'); await page.keyboard.press('e');
  await page.waitForFunction(() => window.__morning.state.character === 'female' && window.__morning.state.mode === 'experience');
  await page.screenshot({ path: 'test-results/03a-hands.png' });
  check('possession starts hands inspection', (await state()).experience === 'hands');
  check('public Alina asset replaces generated model', (await state()).asset === 'Alina.glb');
  check('first person hides all head, hair and mouth interiors', (await state()).headLayers.every(mask=>mask===2));
  await page.keyboard.press('Escape');
  check('possession transfers control and removes duplicate NPC', !(await state()).npc);
  await page.screenshot({ path: 'test-results/03-possessed.png' });
  await page.keyboard.press('v');
  check('first person hides head in main view but keeps it in mirror', (await state()).view === 'first' && (await state()).cameraLayers === 1 && (await state()).reflectedLayers === 3);
  await page.keyboard.press('v');
  await go('mirror'); await page.keyboard.press('e'); await page.waitForTimeout(450);
  check('mirror interaction records experience', (await state()).completed.includes('mirror') && (await state()).mode === 'mirror');
  await page.screenshot({ path: 'test-results/04-mirror-full.png' });
  await page.click('[data-mirror="face"]'); await page.waitForTimeout(550);
  await page.screenshot({ path: 'test-results/05-mirror-face.png' });
  check('face view selected', (await state()).mirrorView === 'face');
  await page.keyboard.press('Escape');
  await go('outfit'); await page.keyboard.press('e'); await page.click('[data-outfit="wine"]');
  check('wardrobe changes outfit and records progress', (await state()).outfit === 'wine' && (await state()).completed.includes('outfit'));
  await go('coffee'); await page.keyboard.press('e');
  check('coffee has a physical cup and pose', (await state()).cupVisible && (await state()).experience === 'coffee');
  await page.waitForTimeout(500); await page.screenshot({ path: 'test-results/coffee-pose.png' });
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => window.__morning.state.completed.includes('coffee'));
  await go('phone'); await page.keyboard.press('e');
  const paused = await state(); await page.keyboard.down('w'); await page.waitForTimeout(350); await page.keyboard.up('w');
  check('dialog stops character movement', (await state()).z === paused.z);
  await page.click('[data-reply="walk"]');
  check('phone reply is saved and reflected in dialogue', (await state()).reply === 'walk' && (await page.locator('#panel-body').innerText()).includes('한강 입구'));
  await page.click('[data-command="resume"]');
  await go('window'); await page.keyboard.press('e');
  check('all five home experiences can be completed', (await state()).completed.length === 5);
  await page.click('[data-command="resume"]');
  await go('outing'); await page.keyboard.press('e');
  check('front door leads to a playable street', (await state()).zone === 'street' && (await state()).completed.includes('outing'));
  const streetBefore=await state();
  await page.keyboard.down('w');
  try { await page.waitForFunction(z=>window.__morning.state.z>z+.4,streetBefore.z,{timeout:5000}); }
  finally { await page.keyboard.up('w'); }
  check('street uses outdoor bounds and character walks', (await state()).z>streetBefore.z+.4);
  await page.screenshot({path:'test-results/street-walk.png'});
  await go('boutique');await page.keyboard.press('e');await page.click('[data-outfit="wine"]');
  check('wardrobe changes the public asset clothing material', (await state()).garments.length===1 && (await state()).garments[0].color==='913e58');
  await go('reflection');await page.keyboard.press('e');await page.waitForTimeout(400);
  await page.screenshot({path:'test-results/shop-reflection.png'});await page.keyboard.press('Escape');
  await go('cafe');await page.keyboard.press('e');
  check('cafe is an enterable interior', (await state()).zone==='cafe');
  await page.screenshot({path:'test-results/cafe-interior.png'});
  await go('order');await page.keyboard.press('e');await page.click('[data-drink="latte"]');await page.click('[data-command="resume"]');
  check('barista order is remembered', (await state()).drink==='latte' && (await state()).completed.includes('order'));
  await go('sit');await page.keyboard.press('e');await page.waitForTimeout(600);
  check('window seat applies seated coffee experience', (await state()).experience==='sit' && (await state()).cupVisible);
  await page.screenshot({path:'test-results/cafe-seated.png'});await page.keyboard.press('Escape');
  await go('street');await page.keyboard.press('e');await go('friend');await page.keyboard.press('e');
  check('friend recognises outfit and message choice', (await page.locator('#panel-body').innerText()).includes('와인색 톱') && (await page.locator('#panel-body').innerText()).includes('산책하자고'));
  await page.click('[data-friend="honest"]');await page.click('[data-command="resume"]');
  check('all nine home and street moments completed', (await state()).completed.length===9);
  await go('home');await page.keyboard.press('e');await page.click('#journal');
  await page.screenshot({ path: 'test-results/06-journal.png' });
  await page.keyboard.press('Escape');
  await page.reload(); await page.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  await page.click('#continue');
  check('reload restores female, outfit, reply and all progress', (await state()).character === 'female' && (await state()).outfit === 'wine' && (await state()).reply === 'walk' && (await state()).completed.length === 9);
  const downloadPromise = page.waitForEvent('download'); await page.keyboard.press('p');
  const download = await downloadPromise;
  check('photo exports a PNG', download.suggestedFilename().endsWith('.png'));
  await go('return'); await page.keyboard.press('e');
  await page.waitForFunction(() => window.__morning.state.character === 'male' && window.__morning.state.mode === 'playing');
  check('return to male preserves experiences and restores NPC', (await state()).npc && (await state()).completed.length === 9);
  await page.click('#pause'); await page.click('[data-command="restart-confirm"]');
  await page.click('[data-command="restart"]');
  check('restart clears progress and restores male', (await state()).completed.length === 0 && (await state()).character === 'male');

  const mobile = await browser.newPage({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true }); track(mobile);
  await mobile.goto('http://127.0.0.1:5176/?test');
  await mobile.waitForSelector('[data-ready="true"]', { timeout: 120000 });
  await mobile.screenshot({ path: 'test-results/07-mobile-intro.png' });
  await mobile.click('#start');
  check('mobile layout has no horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const beforeTouch = await mobile.evaluate(() => window.__morning.state.z);
  const forward = mobile.locator('[data-move="w"]');
  const bounds = await forward.boundingBox();
  await mobile.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2); await mobile.mouse.down();
  await mobile.waitForTimeout(600); await mobile.mouse.up();
  check('mobile directional control moves player', await mobile.evaluate(before => window.__morning.state.z < before - .2, beforeTouch));
  await mobile.evaluate(() => window.__morning.goTo('possess')); await mobile.click('#interact');
  await mobile.waitForFunction(() => window.__morning.state.character === 'female' && window.__morning.state.mode === 'experience');
  await mobile.click('#experience-close');
  await mobile.screenshot({ path: 'test-results/08-mobile-play.png' });
  await mobile.evaluate(() => window.__morning.goTo('mirror')); await mobile.click('#interact');
  await mobile.screenshot({ path: 'test-results/09-mobile-mirror.png' });
  check('mobile mirror exit remains visible', await mobile.locator('#mirror-close').isVisible());
  await mobile.click('#mirror-close'); await mobile.click('#pause');
  check('mobile pause dialog fits screen', await mobile.locator('#panel').evaluate(el => el.getBoundingClientRect().right <= innerWidth));
  await mobile.close();
  check('no asset, browser or WebGL errors', errors.length === 0);
  await writeFile('test-results/results.json', JSON.stringify({ checks, errors }, null, 2));
  console.log(`${checks.length} browser checks passed.`);
} catch (error) {
  await page.screenshot({ path: 'test-results/failure.png' });
  console.error('Browser errors:', errors); throw error;
} finally { await browser.close(); }
